export interface AssetConfig {
  name: string;
  symbol: string;
  pair: string;
  defaultPrice: number;
  decimals: number;
  prefix: string;
  unit: string;
  tickSize: number;
  category: 'forex' | 'cfd' | 'crypto';
}

export const ASSET_REGISTRY: Record<string, AssetConfig> = {
  EURUSD: {
    name: 'EUR / USD',
    symbol: 'EURUSD',
    pair: 'EURUSD',
    defaultPrice: 1.0842,
    decimals: 4,
    prefix: '',
    unit: 'EUR',
    tickSize: 0.0001,
    category: 'forex',
  },
  GBPUSD: {
    name: 'GBP / USD',
    symbol: 'GBPUSD',
    pair: 'GBPUSD',
    defaultPrice: 1.2915,
    decimals: 4,
    prefix: '',
    unit: 'GBP',
    tickSize: 0.0001,
    category: 'forex',
  },
  USDJPY: {
    name: 'USD / JPY',
    symbol: 'USDJPY',
    pair: 'USDJPY',
    defaultPrice: 154.60,
    decimals: 2,
    prefix: '¥',
    unit: 'USD',
    tickSize: 0.01,
    category: 'forex',
  },
  AUDUSD: {
    name: 'AUD / USD',
    symbol: 'AUDUSD',
    pair: 'AUDUSD',
    defaultPrice: 0.6580,
    decimals: 4,
    prefix: '',
    unit: 'AUD',
    tickSize: 0.0001,
    category: 'forex',
  },
  USDCAD: {
    name: 'USD / CAD',
    symbol: 'USDCAD',
    pair: 'USDCAD',
    defaultPrice: 1.3820,
    decimals: 4,
    prefix: '',
    unit: 'USD',
    tickSize: 0.0001,
    category: 'forex',
  },
  USDCHF: {
    name: 'USD / CHF',
    symbol: 'USDCHF',
    pair: 'USDCHF',
    defaultPrice: 0.8840,
    decimals: 4,
    prefix: '',
    unit: 'USD',
    tickSize: 0.0001,
    category: 'forex',
  },
  XAUUSD: {
    name: 'Gold (Emas)',
    symbol: 'XAUUSD',
    pair: 'XAUUSD',
    defaultPrice: 2514.80,
    decimals: 2,
    prefix: '$',
    unit: 'XAU',
    tickSize: 0.1,
    category: 'cfd',
  },
  XAGUSD: {
    name: 'Silver (Perak)',
    symbol: 'XAGUSD',
    pair: 'XAGUSD',
    defaultPrice: 29.45,
    decimals: 2,
    prefix: '$',
    unit: 'XAG',
    tickSize: 0.01,
    category: 'cfd',
  },
  USOIL: {
    name: 'Crude Oil WTI',
    symbol: 'USOIL',
    pair: 'USOIL',
    defaultPrice: 74.60,
    decimals: 2,
    prefix: '$',
    unit: 'BBL',
    tickSize: 0.01,
    category: 'cfd',
  },
  SPX500: {
    name: 'S&P 500 Index',
    symbol: 'SPX500',
    pair: 'SPX500',
    defaultPrice: 5648.40,
    decimals: 2,
    prefix: '$',
    unit: 'PTS',
    tickSize: 0.25,
    category: 'cfd',
  },
  NAS100: {
    name: 'Nasdaq 100',
    symbol: 'NAS100',
    pair: 'NAS100',
    defaultPrice: 19720.50,
    decimals: 2,
    prefix: '$',
    unit: 'PTS',
    tickSize: 0.5,
    category: 'cfd',
  },
  US30: {
    name: 'Dow Jones 30',
    symbol: 'US30',
    pair: 'US30',
    defaultPrice: 41250.00,
    decimals: 2,
    prefix: '$',
    unit: 'PTS',
    tickSize: 1.0,
    category: 'cfd',
  },
  BTCUSDT: {
    name: 'Bitcoin',
    symbol: 'BTC',
    pair: 'BTCUSDT',
    defaultPrice: 75368.45,
    decimals: 2,
    prefix: '$',
    unit: 'BTC',
    tickSize: 1.0,
    category: 'crypto',
  },
  ETHUSDT: {
    name: 'Ethereum',
    symbol: 'ETH',
    pair: 'ETHUSDT',
    defaultPrice: 4149.74,
    decimals: 2,
    prefix: '$',
    unit: 'ETH',
    tickSize: 0.1,
    category: 'crypto',
  },
  LTCUSDT: {
    name: 'Litecoin',
    symbol: 'LTC',
    pair: 'LTCUSDT',
    defaultPrice: 94.92,
    decimals: 2,
    prefix: '$',
    unit: 'LTC',
    tickSize: 0.01,
    category: 'crypto',
  },
  SOLUSDT: {
    name: 'Solana',
    symbol: 'SOL',
    pair: 'SOLUSDT',
    defaultPrice: 175.03,
    decimals: 2,
    prefix: '$',
    unit: 'SOL',
    tickSize: 0.01,
    category: 'crypto',
  },
  BNBUSDT: {
    name: 'Binance',
    symbol: 'BNB',
    pair: 'BNBUSDT',
    defaultPrice: 614.35,
    decimals: 2,
    prefix: '$',
    unit: 'BNB',
    tickSize: 0.05,
    category: 'crypto',
  },
  ADAUSDT: {
    name: 'Cardano',
    symbol: 'ADA',
    pair: 'ADAUSDT',
    defaultPrice: 0.56,
    decimals: 4,
    prefix: '$',
    unit: 'ADA',
    tickSize: 0.0001,
    category: 'crypto',
  },
};

export const getAssetConfig = (symbol: string): AssetConfig => {
  const clean = symbol.replace('USDT', '');
  return (
    ASSET_REGISTRY[symbol] ||
    ASSET_REGISTRY[clean] || {
      name: symbol,
      symbol: clean,
      pair: symbol,
      defaultPrice: 100,
      decimals: 2,
      prefix: '$',
      unit: clean,
      tickSize: 0.01,
      category: 'crypto',
    }
  );
};
